### ISSUE TITLE
Won't build versions newer than 4.14.10

### ISSUE THREAD

**Issue by giantplaceholder** [Layerex/telegram-desktop-patches#5]
Crashes during compiling with versions 4.14.11 and newer. Gets stuck around step 217 during tdesktop build, hangs for around 5-10 minutes than crashes around step 227.

**Comment by olodar** [comment]
> Crashes during compiling with versions 4.14.11 and newer. Gets stuck around step 217 during tdesktop build, hangs for around 5-10 minutes than crashes around step 227.

Are you trying to build old version? It's deprecated. Try my updated PKGBUILD https://github.com/Layerex/telegram-desktop-patches/issues/2#issuecomment-1907783902

I'm not sure about now, but at post's time it worked.

**Comment by olodar** [comment]
> > > Crashes during compiling with versions 4.14.11 and newer. Gets stuck around step 217 during tdesktop build, hangs for around 5-10 minutes than crashes around step 227.
> > 
> > 
> > Are you trying to build old version? It's deprecated. Try my updated PKGBUILD [#2 (comment)](https://github.com/Layerex/telegram-desktop-patches/issues/2#issuecomment-1907783902)
> > I'm not sure about now, but at post's time it worked.
> 
> This works, meaning that it doesn't, just the same as the original PKGBUILD. Both of them are unable to build the binary with versions higher than v4.14.10, with build crashing something like this:
> 
> ```
> [215/1428] /usr/bin/c++ -DBWE_TEST_LOGGING_COMPILE_TIME_ENABLE=0 -DHAVE_WEBRTC_VIDEO -DNO_MAIN_THREAD_WRAPPING -DQT_DEPRECATED_WARNINGS_SINCE=0x051500 -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_KEYWORDS -DRTC_DISABLE_TRACE_EVENTS -DRTC_ENABLE_VP9 -DTGCALLS_USE_STD_OPTIONAL -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_APP_TDESKTOP -DWEBRTC_DUMMY_AUDIO_BUILD -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_HAVE_DCSCTP -DWEBRTC_HAVE_SCTP -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DWEBRTC_LIBRARY_IMPL -DWEBRTC_LINUX -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DWEBRTC_OPUS_SUPPORT_120MS_PTIME=1 -DWEBRTC_OPUS_VARIABLE_COMPLEXITY=0 -DWEBRTC_POSIX -DWEBRTC_USE_BUILTIN_ISAC_FLOAT -DWEBRTC_USE_H264 -DWEBRTC_USE_PIPEWIRE -DWEBRTC_USE_X11 -I<full_path_to_dir>telegram-desktop-patches/src/tdesktop-4.14.16-full/Telegram/ThirdParty/tgcalls -I<full_path_to_dir>telegram-desktop-patches/src/tdesktop-4.14.16-full/Telegram/ThirdParty/tgcalls/tgcalls -isystem /usr/include/tg_owt -isystem /usr/include/tg_owt/third_party/libyuv/include -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -ffat-lto-objects -O3 -DNDEBUG -std=gnu++20 -Wno-deprecated-volatile -Wno-ambiguous-reversed-operator -Wno-deprecated-declarations -Wno-unqualified-std-cast-call -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -MD -MT Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o -MF Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o.d -o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o -c <full_path_to_dir>telegram-desktop-patches/src/tdesktop-4.14.16-full/Telegram/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp
> [216/1428] : && /usr/bin/cmake -E rm -f Telegram/liblib_tgcalls.a && /usr/bin/ar qc Telegram/liblib_tgcalls.a  Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/Instance.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/AudioDeviceHelper.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/ChannelManager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/CodecSelectHelper.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/CryptoHelper.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/EncryptedConnection.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/FakeAudioDeviceModule.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/FieldTrialsConfig.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/InstanceImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/LogSinkImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/Manager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/MediaManager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/Message.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/NetworkManager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/SctpDataChannelProviderInterfaceImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/StaticThreads.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/TurnCustomizerImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/VideoCaptureInterface.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/VideoCaptureInterfaceImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/utils/gzip.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/ContentNegotiation.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/DirectNetworkingImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/ExternalSignalingConnection.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/InstanceV2ReferenceImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/InstanceV2Impl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/NativeNetworkingImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/ReflectorPort.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/ReflectorRelayPortFactory.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/Signaling.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/SignalingConnection.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/SignalingEncryption.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2/SignalingSctpConnection.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2_4_0_0/InstanceV2_4_0_0Impl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/v2_4_0_0/Signaling_4_0_0.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/desktop_capturer/DesktopCaptureSource.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/desktop_capturer/DesktopCaptureSourceHelper.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/desktop_capturer/DesktopCaptureSourceManager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/AVIOContextImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/AudioStreamingPart.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/AudioStreamingPartInternal.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/AudioStreamingPartPersistentDecoder.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupInstanceCustomImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupJoinPayloadInternal.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/GroupNetworkManager.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/StreamingMediaContext.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/group/VideoStreamingPart.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/platform/tdesktop/DesktopInterface.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/platform/tdesktop/VideoCapturerInterfaceImpl.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/platform/tdesktop/VideoCapturerTrackSource.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/platform/tdesktop/VideoCameraCapturer.cpp.o Telegram/CMakeFiles/lib_tgcalls.dir/ThirdParty/tgcalls/tgcalls/third-party/json11.cpp.o && /usr/bin/ranlib Telegram/liblib_tgcalls.a && :
> [217/1428] : && /usr/bin/cmake -E rm -f Telegram/liblib_tgcalls_legacy.a && /usr/bin/ar qc Telegram/liblib_tgcalls_legacy.a  Telegram/CMakeFiles/lib_tgcalls_legacy.dir/ThirdParty/tgcalls/tgcalls/legacy/InstanceImplLegacy.cpp.o && /usr/bin/ranlib Telegram/liblib_tgcalls_legacy.a && :
> ```

Hi, here's my cloned repo https://github.com/olodar/telegram-desktop-patches
Updated, working with 29/5/24 arch.
It seems @Layerex will not update anymore, so I deciced to make a clone, sometimes will update, but not often.

**Comment by Layerex** [comment]
Noted RAM requirement in README in https://github.com/Layerex/telegram-desktop-patches/commit/98f3a04a585520355f1dbf22a3b748521f34c888
